### ISSUE TITLE
no new line at end of output if no sep char at end of string

### ISSUE THREAD

**Issue by Alexdelia** [AdrianWeaver/rush_yasl#1]
Yo, idk if your split is finished, but there is one issue:

![image](https://user-images.githubusercontent.com/60811847/162593820-f7b7deee-0f3e-473f-a313-8d928f9de1aa.png)

example:
```bash
./yasl_split e llezz
ll$
zz%
```

but work if:
```bash
./yasl_split e llezze
ll$
zz$
%
```
and
```bash
./yasl_split e eelleezzee
ll$
zz$
%
```

**Comment by Alexdelia** [comment]
mais gros gg pour le split court et clean!

**Comment by AdrianWeaver** [comment]
Thanks a lot for the feedback, this is an issue indeed, will have a look at it today ! :D

**Comment by AdrianWeaver** [comment]
Issue fixed by adding a default 2:print after the loop.
The pile_2 would have by default either a null character or a \n so this should fix without adding unexpected behaviours.
Thanks for finding it :)
